### ISSUE TITLE
How to extract each character from the image?

### ISSUE THREAD

**Issue by kushal-chakraborty** [dishank-b/Character_Segmentation#3]
I have done something like this.

`for cnt in contours:
if cv2.contourArea(cnt) > 20:
x,y,w,h = cv2.boundingRect(cnt)
cv2.rectangle(src_img,(x,y),(x+w,y+h),(0,0,0),1)
plt.figure()
plt.imshow(cv2.resize(src_img[y+2:y+h-2,x+2:x+h-2],(25,25)))
plt.show()

showimages()`

**Comment by dishank-b** [comment]
@kushal-chakraborty . It seems like the right way.
